### ISSUE TITLE
请问大佬，一直报这个错误是什么原因？list index out of range

### ISSUE THREAD

**Issue by Hailii** [ChaXxl/GZHU_LibraryAutoReserve_sign#11]

**Comment by ChaXxl** [comment]
如果用的是最新的代码，那就不是 bug，只有两个原因：
1. 密码输入错了
2. 登录教务系统，它要求改密码，改一下就行了

**Comment by Hailii** [comment]
> 如果用的是最新的代码，那就不是 bug，只有两个原因：
> 
> 1. 密码输入错了
> 2. 登录教务系统，它要求改密码，改一下就行了

解决了，非常感谢！！
