### ISSUE TITLE
预约或者签到的时候偶尔会连接超时有什么头绪嘛

### ISSUE THREAD

**Issue by Raiscies** [ChaXxl/GZHU_LibraryAutoReserve_sign#14]
脚本是部署在github action上的, 最近在预约或者签到的时候, 偶尔会发生连接超时, 报错显示的是get_login_url()这里开始就没法连接上了, 大致的traceback如下(代码有修改过, 所以行号什么的应该和源文件不一样).

```
 Traceback (most recent call last):
  File "/home/runner/work/gzhu-libbooker/gzhu-libbooker/reserve.py", line 115, in do_reserve_for_one
    yy.get_login_url()
  File "/home/runner/work/gzhu-libbooker/gzhu-libbooker/libs/source.py", line 249, in get_login_url
    address = self.rr.get(url=url, params=params, timeout=60).json().get('data')
  ... 以下省略
  httpcore.ConnectTimeout: timed out
```
这个是在获取登录地址的时候就发生超时, 而且一旦发生, 除非重新拉起一个action workflow, 否则无论怎么重试都是超时的. 请问有什么头绪嘛? 有没有可能是学校屏蔽掉了一些ip, 而脚本执行的时候恰好就在被屏蔽的ip里面. 又或者是其它什么原因呢?

**Comment by ChaXxl** [comment]
去数字广大看下是不是要改密码

**Comment by Raiscies** [comment]
好的，谢谢提醒

**Comment by Raiscies** [comment]
你好, 在数字广大上没有看到密码过期的提示呀, 而且这个超时是在登录之前就发生的, 应该跟密码过期无关吧，而且这个是偶发性的，有时会超时，有时又不会，就很奇怪

**Comment by ChaXxl** [comment]
我这边有出现过超时，但比较少，不确定是不是 IP 问题，可以试试用云函数

**Comment by Raiscies** [comment]
了解了，谢谢✨
