### ISSUE TITLE
可以改进一下吗 签到失败什么的时候可以在pluspush推送吗

### ISSUE THREAD

**Issue by JJUNLANG** [ChaXxl/GZHU_LibraryAutoReserve_sign#2]

**Comment by decike** [comment]
请提供一下日志

**Comment by decike** [comment]
pushplus可以搞，晚上吧

**Comment by decike** [comment]
搞不完XD，有点事。明天一定搞，搞不出来你揍我

**Comment by JJUNLANG** [comment]
> 搞不完XD，有点事。明天一定搞，搞不出来你揍我

没事哈哈 看你有空再弄也行

**Comment by JJUNLANG** [comment]
PS C:\Users\19781\Desktop\GZHU_LibraryAutoReserve_sign-main> python sign.py
__init__() missing 1 required positional argument: 'periods'

这个新更新的签到好像有点问题的，你也看看吧。我一直用的是旧版本的，那个没问题

**Comment by decike** [comment]
没道理，我应该没动过签到部分

**Comment by decike** [comment]
明天看明天看

**Comment by decike** [comment]
改好了，修复了签到不能用的bug，新增了pushplus，issue先关了，有别的错误可以再提新的issue
