### ISSUE TITLE
想问一下个人电脑问题

### ISSUE THREAD

**Issue by JJUNLANG** [ChaXxl/GZHU_LibraryAutoReserve_sign#8]
以前在本地电脑运行这个PY好好的，可以显示出运行结果，最近啥都没干，就报错这个编码问题是什么情况，怎么解决。
![image](https://github.com/ChaXxl/GZHU_LibraryAutoReserve_sign/assets/112674337/f310991d-48ad-4f9a-8f9c-8656f0e06482)

**Comment by ChaXxl** [comment]
我改了，电脑运行的话用 main 分支，另一个分支是用 Github Action 运行的

**Comment by JJUNLANG** [comment]
我用的旧版本也会提示这个。前几天可以在本地调试再加到服务器。在服务器可以正常运行，在本地运行就不行了。不知道是啥原因，我也没动过电脑

**Comment by ChaXxl** [comment]
之前的是有 bug，我改了，现在 main分支代码是最新的，运行也是正常的，建议使用最新版代码。Github Action 那个分支还不更新

> 我用的旧版本也会提示这个。前几天可以在本地调试再加到服务器。在服务器可以正常运行，在本地运行就不行了。不知道是啥原因，我也没动过电脑

**Comment by JJUNLANG** [comment]
意思就是出现这个编码问题不是因为我的电脑python的原因吗> 之前的是有 bug，我改了，现在 main分支代码是最新的，运行也是正常的，建议使用最新版代码。Github Action 那个分支还不更新
> 
> 
> 
> > 我用的旧版本也会提示这个。前几天可以在本地调试再加到服务器。在服务器可以正常运行，在本地运行就不行了。不知道是啥原因，我也没动过电脑
> 
> 
> 
>

**Comment by ChaXxl** [comment]
是的

> 意思就是出现这个编码问题不是因为我的电脑python的原因吗> 之前的是有 bug，我改了，现在 main分支代码是最新的，运行也是正常的，建议使用最新版代码。Github Action 那个分支还不更新
> 
> > > 我用的旧版本也会提示这个。前几天可以在本地调试再加到服务器。在服务器可以正常运行，在本地运行就不行了。不知道是啥原因，我也没动过电脑
